import '../styles/globals.css'
import type { AppProps } from 'next/app'
import CursorProvider from '../context/CursorContext'
import ScrollerProvider from '../context/ScrollWrapperContext'
import MenuContext from '../context/MenuContext'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ScrollerProvider>
      <CursorProvider>
        <MenuContext>
          <Head>
            <title>GraphicHunters - The Creative Studio Focused on Sports</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.svg" />
          </Head>
          <Component {...pageProps} />
        </MenuContext>        
      </CursorProvider>
    </ScrollerProvider>  
  )
  
}

export default MyApp
