import '../styles/globals.css'
import type { AppProps } from 'next/app'
import CursorProvider from '../context/CursorContext'
import ScrollerProvider from '../context/ScrollWrapperContext'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ScrollerProvider>
      <CursorProvider>
        <Head>
          <title>GraphicHunters - The Creative Studio Focused on Sports</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.svg" />
        </Head>
        <Component {...pageProps} />
      </CursorProvider>
    </ScrollerProvider>  
  )
  
}

export default MyApp
