import React from 'react'
import Layout from '../components/Layout'
import Contact from '../components/pages/Contact'
import Head from 'next/head'
import PreloaderWrapper from '../components/preloaders/PreloaderWrapper'

function HomePage() 
{  
  return (
    <div>      
      <Head>
          <title>GraphicHunters - The Creative Studio Focused on Sports</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.svg" />
      </Head>        
      <PreloaderWrapper>
        <Layout blackSide={true} contact={true}>
          <Contact/>
        </Layout>
      </PreloaderWrapper>      
    </div>
  )
}

export default HomePage

