import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import ScrollWrapper from '../components/ScrollWrapper'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ScrollWrapper>
        <div>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus velit debitis numquam odio aut distinctio eligendi sed possimus, accusamus blanditiis officiis, maiores officia eaque neque. Quod dignissimos id maiores? Non.
          Fugit debitis corrupti repellendus amet optio recusandae architecto rerum laboriosam? Corrupti officiis eius necessitatibus beatae architecto alias illo eos nemo consequatur numquam sint assumenda, autem ut et similique quos ea?
          Veniam pariatur quas molestiae ea mollitia aliquid adipisci, non, maiores expedita, unde necessitatibus ex perferendis tempora aperiam vel numquam eligendi dolore totam provident! Pariatur incidunt, officia molestias assumenda illum illo.
          Cupiditate consequuntur soluta perferendis voluptate inventore, unde nam totam quibusdam. Nesciunt autem odit, nulla ducimus sapiente sed, eligendi dolore, maxime inventore recusandae est quae corrupti eos veniam vero! Cum, eius.
          Mollitia soluta, dolore necessitatibus cum perspiciatis et consequuntur laborum natus sint laudantium eveniet eaque earum eligendi quas repudiandae reprehenderit, eius maiores veniam? Magni error saepe commodi distinctio molestias. Deserunt, quasi?
          Libero architecto consectetur tempora vel veritatis necessitatibus veniam molestiae et quia ea modi nostrum quo laborum laboriosam perferendis, quas esse iure doloribus illo commodi molestias iusto placeat inventore. Modi, doloremque.
          Soluta ducimus laudantium, debitis, corrupti adipisci perspiciatis incidunt architecto reprehenderit dolorem, iste aut. Quo cum totam aspernatur nemo vitae, vero, id possimus perferendis accusantium culpa numquam perspiciatis in optio dolores?
          Reprehenderit, tempore recusandae libero eius harum magni itaque iste eaque beatae cumque accusamus natus labore aliquam at maxime dolorum! Facilis molestiae illo iure blanditiis voluptas cupiditate ratione quas nihil rerum!
          Amet inventore provident deserunt rem voluptates dolores modi reprehenderit cumque aut optio magni rerum eos vel culpa asperiores voluptas placeat, quisquam voluptatem velit recusandae nobis. A quaerat aliquam magnam! Expedita!
          Ab mollitia architecto sed maiores nostrum qui, dicta id aliquam repellendus itaque eveniet ratione eligendi et incidunt, dolorum perspiciatis corrupti, cumque magni culpa ad! Nesciunt dicta alias debitis eligendi vitae.
          Magni numquam explicabo harum excepturi, omnis libero at laudantium nemo mollitia, quas iure. Mollitia quidem dolore est accusantium. Quam sunt repellendus ullam obcaecati esse ea natus possimus eaque eligendi soluta.
          Nemo possimus neque ea at exercitationem eum odio vitae accusantium cumque nostrum pariatur perferendis consequatur, amet inventore, saepe natus laudantium consectetur quo a alias placeat ex delectus! Cumque, esse recusandae.
          Odit, magni incidunt dicta accusantium voluptate animi aliquid veniam eos nulla, nobis, natus culpa aspernatur reiciendis soluta omnis officia cum reprehenderit aliquam quas praesentium deserunt. Nam dolorum nihil culpa quidem.
          Consequatur neque dolor optio eum ex rem fuga possimus magni facilis ducimus debitis, doloremque voluptates! Velit deserunt quas a. Reiciendis pariatur optio ea odio. Alias tempora eaque dolores quam dicta.
          Obcaecati quas, sed placeat exercitationem tempora molestias. Facilis quisquam totam alias temporibus ad vel neque placeat labore minima unde ipsum obcaecati veniam, ipsam sapiente non ullam, natus minus ab aut?
          Alias facere obcaecati libero nisi magni odio fuga nihil aperiam provident voluptate dignissimos fugit assumenda quam accusantium, hic nemo delectus, veniam suscipit aut. Neque aut nesciunt officiis, dolorem non blanditiis.
          Quas inventore quo minus debitis quae veniam, harum unde expedita repellendus dolore incidunt vel ab atque, quisquam voluptates commodi. Libero quod sint aspernatur quidem ex velit tenetur minus repudiandae sequi?
          Dolores expedita distinctio, ad dolorum, in aliquid eos hic voluptatem nostrum fugit numquam ea dignissimos illum, repellendus blanditiis sed modi. Similique minus sequi perferendis possimus officiis commodi cum ab odit.
          Voluptatibus facilis, itaque nulla et natus molestias non odit maiores aperiam est nostrum dolorem aut laboriosam consectetur ipsa, quasi adipisci dicta voluptas exercitationem ad facere consequuntur architecto aliquid repudiandae? Id.
          Non error quis illo aliquid perferendis dolorem, et voluptas porro enim itaque deleniti at explicabo cum ex natus quos voluptatibus. Suscipit culpa unde soluta? Non debitis excepturi quisquam rerum est.
          Odit id nemo consequatur, beatae rem cupiditate at optio qui quam veritatis corrupti aperiam maxime, praesentium libero? Consequatur neque velit sequi, tempore obcaecati id, ducimus odio ut, inventore nisi molestiae!
          Ratione id, minus aliquam ab dolorem distinctio. Doloribus nisi tempora ullam a obcaecati vero voluptatem aspernatur architecto, dignissimos eius? Distinctio temporibus vero at, aspernatur accusamus fuga dolor? Consequuntur, eius eum.
          Amet eos adipisci sed vitae ipsam quasi! Neque alias eos ex! Pariatur quos sequi eveniet commodi eum earum accusantium consequuntur. Molestiae, placeat? Sequi, maxime repellat ducimus tenetur praesentium ex veritatis.
          Consequatur quasi voluptatibus porro vero, laudantium tenetur neque, eveniet beatae delectus accusantium velit, dolorum earum minima! Ab consequatur quibusdam vel similique, tempore, totam eveniet nisi, quod iusto odit dolor illo.
          Laudantium, ab sit in, quaerat fuga recusandae magnam fugiat repudiandae laboriosam delectus ducimus cum laborum placeat eius sunt voluptate quidem beatae aliquid, exercitationem voluptas dolorem cumque quis? Earum, provident nihil.
          Ratione dignissimos laudantium adipisci quod molestias iure. Corporis molestiae magnam aspernatur animi doloremque quibusdam possimus incidunt ex? Excepturi dolorum eius eaque, aliquid, sit sequi doloribus repudiandae deleniti enim sint fugiat.
          Harum, consequuntur magnam totam nemo suscipit quod vel itaque natus beatae blanditiis! Est nobis praesentium tempore necessitatibus vero fugiat nihil rem quam consequuntur reiciendis ad natus minima, ex, provident delectus!
          Consequuntur nulla tempore dolore dicta nesciunt, iste quas nisi consequatur officiis? Tempora praesentium facilis dolorem nulla dignissimos, in tenetur voluptatum quidem esse fugit dicta at molestias quia non numquam. Facere!
          Quo nobis id aliquam! Soluta, expedita facere ullam dolorum quod porro, perferendis quasi ex, corrupti ducimus nihil hic totam aspernatur rem libero. Dignissimos voluptates tempore minima ad labore, nisi iure.
          Totam eligendi, delectus obcaecati dolorum quidem asperiores qui fugit eos, soluta distinctio autem. Iusto distinctio incidunt architecto at consequatur, totam temporibus vel. Doloribus, impedit aspernatur ducimus neque ipsa aliquam fuga?
          Ipsa quo voluptates reprehenderit! Quis nam nisi quidem fuga? Sequi fugiat eum placeat reiciendis excepturi quis minima dicta consectetur atque. Sed ducimus beatae reiciendis consequatur hic deleniti error ipsum magnam.
          Quae nihil repellendus cumque fugiat officia hic labore aliquam nobis. Beatae, nemo. Consequatur nostrum dolores laboriosam dolor voluptates? Ut aperiam ipsum et ducimus error natus consequatur aliquid odit magnam excepturi!
          Recusandae quasi voluptas animi sequi accusantium fugit enim corporis rem facere, dicta alias eveniet saepe obcaecati quaerat cumque delectus corrupti, reiciendis laborum. Rem eius, dolores pariatur numquam ea sequi quae!
          Similique molestiae sunt iure exercitationem quia doloribus officia itaque facilis maiores cumque, magni repellat aliquam incidunt perferendis mollitia neque sed ab placeat libero necessitatibus! Ullam hic maiores nesciunt porro consequuntur.
          Autem recusandae at illo est rerum? Suscipit, non quam. Necessitatibus est architecto, eaque voluptatem sunt ipsa sapiente commodi, autem sed soluta ad incidunt error voluptas labore aliquid quod, ut animi!
          Voluptas repellendus minima dolorum. Nisi ipsam voluptatum veniam et suscipit nemo placeat voluptates doloremque adipisci sunt, consequatur ex earum sapiente, animi impedit voluptatibus similique accusamus perspiciatis consequuntur totam quisquam in?
          Voluptas ducimus doloremque dolores deserunt repellendus autem corporis, perferendis, necessitatibus architecto voluptatem nisi accusamus illo commodi aliquid, amet veniam at placeat fuga vel iste mollitia maiores sapiente sequi? Sed, animi?
          Odio, modi cupiditate quaerat a quidem quisquam autem magnam corporis, animi provident eaque, cumque suscipit perspiciatis molestiae tempore aspernatur eum dolorem fugiat? Eligendi harum facere totam asperiores fugiat eum rerum.
          Voluptatem praesentium ducimus exercitationem cum, blanditiis maiores aliquam sunt quos! Quia officia eveniet ex vero doloribus officiis culpa reprehenderit, eligendi obcaecati similique deleniti mollitia explicabo quae! Quae dicta minus aliquam!
          Saepe tempore laboriosam facere facilis cum. Asperiores repellendus enim illum illo minima voluptates, dolorem ex consectetur, amet distinctio voluptatibus? Ut nulla aperiam necessitatibus id corporis enim sit velit repellendus vero.
          Odit deserunt consequatur, culpa architecto dicta, deleniti est unde, nesciunt aperiam numquam vitae dolores aut accusamus at magni? Quae, asperiores perferendis voluptas beatae quisquam odio similique a expedita laboriosam aspernatur.
          Quod alias assumenda et ipsum, sed earum quidem. Dicta minus, facilis dolor corporis quod explicabo, deserunt perspiciatis, nostrum quae vero fugit iste doloremque magnam voluptatibus cum. Dignissimos nam nisi provident.
          Explicabo veniam necessitatibus iste tempora reprehenderit cumque commodi quam voluptatum dolore reiciendis pariatur perspiciatis expedita nulla a ipsa, rem voluptatem soluta vitae debitis, quasi, aliquid mollitia omnis. Voluptas, ut eos.
          Vero architecto totam nostrum sapiente at quaerat cumque eligendi et eius natus id eos, a aut nihil rerum amet autem magnam doloremque repudiandae iure molestias! Odio, blanditiis ab? Itaque, rem.
          Rerum incidunt officiis velit asperiores optio recusandae necessitatibus aliquid, tempore molestias alias placeat autem laudantium iusto laboriosam aliquam repellat ipsum aut culpa blanditiis voluptate. Ipsam unde architecto aut amet totam!
          Itaque rerum esse corrupti dolor dolorum, et soluta, odio optio recusandae quibusdam ducimus non eius quas fugit labore. Iste, officia autem rerum ab amet quaerat molestiae numquam possimus quo suscipit?
          Ipsam quisquam voluptates maiores non dignissimos aliquid soluta dolor culpa quas eveniet aperiam atque totam saepe officia, ipsa dolorem placeat cupiditate, cumque beatae perferendis dicta nobis voluptatibus in earum. Hic.
          Omnis ad impedit molestias commodi ab unde iure exercitationem aut et cupiditate? Culpa reprehenderit hic esse autem sit ad aliquam molestiae nemo, quisquam assumenda. Maiores quos delectus repellendus rem accusamus!
          Minus, impedit exercitationem nostrum, ducimus dolore autem pariatur reprehenderit officiis, fugiat necessitatibus ratione quasi possimus facere ullam magni nobis. Mollitia harum accusantium ipsa animi quo aut incidunt, sit reiciendis. Harum.
          Numquam similique aspernatur, quidem fugit quisquam cupiditate amet incidunt illum aliquam in voluptas deserunt molestias placeat a! Maxime assumenda ex animi provident possimus neque! Esse quis atque facilis placeat amet.
          Mollitia, sunt sint voluptatum consequuntur nihil enim in ea ducimus iste porro nobis veritatis optio vel architecto alias accusamus quos tenetur quidem corrupti. Cumque dolorem dolore unde illo, perferendis facilis.
          Ipsa id maiores sapiente expedita ex modi quos mollitia, tempore possimus voluptate, voluptatum quaerat, quam voluptatem alias dolore suscipit minus? Vitae, officiis magni. Doloremque, inventore aspernatur nostrum illum eligendi necessitatibus.
          Inventore eligendi error voluptate consequuntur. Quisquam neque aperiam eveniet perferendis iure vel aliquam necessitatibus odio veniam similique dolorum magni modi officiis minus voluptates, voluptatem nemo et earum, minima laborum eum?
          Voluptatibus quaerat dolore excepturi reprehenderit adipisci impedit nisi, id soluta repellat optio sequi repellendus laudantium in voluptates? Deleniti assumenda quisquam temporibus. Quam a debitis quidem minima, perspiciatis consectetur unde quisquam!
          Consectetur veniam ipsam quae vitae ea eius illum dolor repudiandae laboriosam, officiis doloremque eligendi temporibus quas exercitationem blanditiis modi labore voluptas id eveniet optio. Ut deleniti similique aperiam! Ducimus, alias.
          Illo cupiditate exercitationem repellendus, est architecto nostrum odio explicabo sapiente nihil quidem voluptatum, quas culpa facere debitis doloremque vero nobis maiores soluta, magnam facilis neque quaerat. Fugiat quisquam in iste!
          Numquam necessitatibus repellat dignissimos impedit hic, quis nisi voluptatem tempore, iste maiores, aperiam totam labore nesciunt sint earum explicabo cupiditate sunt debitis deserunt voluptates? Similique eligendi fuga natus ut ipsa.
          Iste atque voluptatem explicabo voluptas velit? Accusantium provident maiores consequuntur hic sit rem corrupti ex libero at quisquam sapiente atque numquam nostrum odio quam minima quo impedit assumenda, alias dolorem.
          Veritatis ratione similique, ipsa dicta ex eum necessitatibus error deserunt, voluptas illum quod repellat aut. Deleniti tenetur, veritatis voluptate libero et, reprehenderit quae, alias incidunt perferendis cupiditate repellat rem commodi!
          Veritatis in recusandae odio facere consectetur excepturi reprehenderit consequuntur at necessitatibus expedita nostrum voluptate, amet quisquam aut et quia eius ipsam cum repellendus atque adipisci ex! Reiciendis dolores omnis quasi!
        </div>
      </ScrollWrapper>            

    </div>
  )
}

export default Home
