import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import styled from "styled-components"

const Home: NextPage = () => {

  const [started,setStarted] = useState(false);

  const Button = styled.button`
    padding: 1rem 2rem;
    border: 1px solid red;
    color: ${started ? 'red' : 'white'};
    background: ${started ? 'white' : 'red'};
    cursor: pointer;
  `
  

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div><h1>hello next js</h1></div>
      <Button onClick={()=>setStarted(start=>!start)}>start</Button>

    </div>
  )
}

export default Home
