import React from 'react'
import Layout from '../components/Layout'
import Studio from '../components/pages/Studio'
import PreloaderWrapper from '../components/preloaders/PreloaderWrapper'
import Head from 'next/head'

export default function StudioPage() {
  return (
    <div>
        <Head>
            <title>Studio - GraphicHunters</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.svg" />
        </Head>
        <PreloaderWrapper>
          <Layout blackFooter={true} blackSide={true}>
              <Studio/>
          </Layout>
        </PreloaderWrapper>        
    </div>
  )
}
