import React from 'react'
import Layout from '../components/Layout'
import Studio from '../components/pages/Studio'
import Head from 'next/head'

export default function StudioPage() {
  return (
    <div>
        <Head>
            <title>Studio - GraphicHunters</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.svg" />
        </Head>
        <Layout blackFooter={true} blackSide={true}>
            <Studio/>
        </Layout>
    </div>
  )
}
