import React from 'react'
import Layout from '../components/Layout'
import { request } from "../lib/datocms";
import DataInterface from '../types/DataInterface';
import Work from '../components/pages/Work';
import Head from 'next/head';

export default function WorkPage({data}:{data:DataInterface}) {
  return (
    <div>
        <Head>
            <title>Work - GraphicHunters</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.svg" />
        </Head>
        <Layout blackFooter={true}>
            <Work data={data}/>
        </Layout>
    </div>
  )
}


const WORKPAGE_QUERY = `{
    allWorks {
      id
      title
      desc
      slug
      laoder {hex}
      image {url}
      _status
      _firstPublishedAt
    }
    _allWorksMeta {
      count
    }
  }`;
  
  export async function getStaticProps() {
    const data = await request({
      query: WORKPAGE_QUERY,
      variables: { limit: 10 }
    });
    return {
      props: { data }
    };
  }